services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boilerolate
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./packages/backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:root@postgres:5432/boilerolate?schema=public"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./packages/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
